// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWordsBatch(arg1) {
  return window['go']['main']['App']['AddWordsBatch'](arg1);
}

export function CacheSubtitles(arg1, arg2) {
  return window['go']['main']['App']['CacheSubtitles'](arg1, arg2);
}

export function DbClear() {
  return window['go']['main']['App']['DbClear']();
}

export function DbDictAddToWordList(arg1) {
  return window['go']['main']['App']['DbDictAddToWordList'](arg1);
}

export function DbDictGetProgress(arg1) {
  return window['go']['main']['App']['DbDictGetProgress'](arg1);
}

export function DbDictSaveProgress(arg1, arg2) {
  return window['go']['main']['App']['DbDictSaveProgress'](arg1, arg2);
}

export function DbDictTags() {
  return window['go']['main']['App']['DbDictTags']();
}

export function DbDictWords(arg1) {
  return window['go']['main']['App']['DbDictWords'](arg1);
}

export function DbExport() {
  return window['go']['main']['App']['DbExport']();
}

export function DbImport(arg1) {
  return window['go']['main']['App']['DbImport'](arg1);
}

export function DbTagsAdd(arg1, arg2) {
  return window['go']['main']['App']['DbTagsAdd'](arg1, arg2);
}

export function DbTagsDelete(arg1) {
  return window['go']['main']['App']['DbTagsDelete'](arg1);
}

export function DbTagsList() {
  return window['go']['main']['App']['DbTagsList']();
}

export function DbWordsAdd(arg1) {
  return window['go']['main']['App']['DbWordsAdd'](arg1);
}

export function DbWordsDelete(arg1) {
  return window['go']['main']['App']['DbWordsDelete'](arg1);
}

export function DbWordsDeleteBatch(arg1) {
  return window['go']['main']['App']['DbWordsDeleteBatch'](arg1);
}

export function DbWordsGetReview() {
  return window['go']['main']['App']['DbWordsGetReview']();
}

export function DbWordsGetReviewCount() {
  return window['go']['main']['App']['DbWordsGetReviewCount']();
}

export function DbWordsList() {
  return window['go']['main']['App']['DbWordsList']();
}

export function DbWordsSearch(arg1) {
  return window['go']['main']['App']['DbWordsSearch'](arg1);
}

export function DbWordsUpdate(arg1, arg2) {
  return window['go']['main']['App']['DbWordsUpdate'](arg1, arg2);
}

export function DownloadWhisperModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadWhisperModel'](arg1, arg2);
}

export function FolderCreate(arg1, arg2) {
  return window['go']['main']['App']['FolderCreate'](arg1, arg2);
}

export function FolderDelete(arg1) {
  return window['go']['main']['App']['FolderDelete'](arg1);
}

export function FolderRename(arg1, arg2) {
  return window['go']['main']['App']['FolderRename'](arg1, arg2);
}

export function GetAllTypingProgress() {
  return window['go']['main']['App']['GetAllTypingProgress']();
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetArticles(arg1) {
  return window['go']['main']['App']['GetArticles'](arg1);
}

export function GetCachedSubtitles(arg1) {
  return window['go']['main']['App']['GetCachedSubtitles'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetMediaPort() {
  return window['go']['main']['App']['GetMediaPort']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetTypingProgress(arg1, arg2) {
  return window['go']['main']['App']['GetTypingProgress'](arg1, arg2);
}

export function GetTypingRecords(arg1) {
  return window['go']['main']['App']['GetTypingRecords'](arg1);
}

export function GetVideoThumbnail(arg1) {
  return window['go']['main']['App']['GetVideoThumbnail'](arg1);
}

export function GetWaveformData(arg1) {
  return window['go']['main']['App']['GetWaveformData'](arg1);
}

export function GetWhisperLang() {
  return window['go']['main']['App']['GetWhisperLang']();
}

export function LibraryImport(arg1, arg2) {
  return window['go']['main']['App']['LibraryImport'](arg1, arg2);
}

export function LibraryList() {
  return window['go']['main']['App']['LibraryList']();
}

export function LibraryMove(arg1, arg2) {
  return window['go']['main']['App']['LibraryMove'](arg1, arg2);
}

export function LibraryRemove(arg1) {
  return window['go']['main']['App']['LibraryRemove'](arg1);
}

export function LibraryRename(arg1, arg2) {
  return window['go']['main']['App']['LibraryRename'](arg1, arg2);
}

export function ListWhisperModels() {
  return window['go']['main']['App']['ListWhisperModels']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenSubtitle() {
  return window['go']['main']['App']['OpenSubtitle']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RecentAdd(arg1) {
  return window['go']['main']['App']['RecentAdd'](arg1);
}

export function RecentList() {
  return window['go']['main']['App']['RecentList']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveTypingProgress(arg1) {
  return window['go']['main']['App']['SaveTypingProgress'](arg1);
}

export function SaveTypingRecord(arg1) {
  return window['go']['main']['App']['SaveTypingRecord'](arg1);
}

export function SetWhisperLang(arg1) {
  return window['go']['main']['App']['SetWhisperLang'](arg1);
}

export function SetWhisperModel(arg1) {
  return window['go']['main']['App']['SetWhisperModel'](arg1);
}

export function Transcribe(arg1) {
  return window['go']['main']['App']['Transcribe'](arg1);
}

export function WhisperStatus() {
  return window['go']['main']['App']['WhisperStatus']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
