// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dict} from '../models';

export function CacheSubtitles(arg1:string,arg2:string):Promise<void>;

export function DbClear():Promise<void>;

export function DbDictAddToWordList(arg1:string):Promise<main.DictAddResult>;

export function DbDictGetProgress(arg1:string):Promise<number>;

export function DbDictSaveProgress(arg1:string,arg2:number):Promise<void>;

export function DbDictTags():Promise<Array<dict.DictTag>>;

export function DbDictWords(arg1:string):Promise<Array<dict.DictWord>>;

export function DbExport():Promise<string>;

export function DbImport(arg1:string):Promise<main.ImportResult>;

export function DbTagsAdd(arg1:string,arg2:string):Promise<number>;

export function DbTagsDelete(arg1:number):Promise<void>;

export function DbTagsList():Promise<Array<main.Tag>>;

export function DbWordsAdd(arg1:string):Promise<number>;

export function DbWordsDelete(arg1:number):Promise<void>;

export function DbWordsDeleteBatch(arg1:Array<number>):Promise<void>;

export function DbWordsGetReview():Promise<Array<main.Word>>;

export function DbWordsList():Promise<Array<main.Word>>;

export function DbWordsSearch(arg1:string):Promise<Array<main.Word>>;

export function DbWordsUpdate(arg1:number,arg2:string):Promise<void>;

export function DownloadWhisperModel(arg1:string,arg2:string):Promise<void>;

export function GetCachedSubtitles(arg1:string):Promise<string>;

export function GetDownloadProgress():Promise<string>;

export function GetMediaPort():Promise<number>;

export function GetPlatform():Promise<string>;

export function GetVideoThumbnail(arg1:string):Promise<string>;

export function GetWhisperLang():Promise<string>;

export function ListWhisperModels():Promise<string>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenSubtitle():Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RecentAdd(arg1:string):Promise<string>;

export function RecentList():Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function SetWhisperLang(arg1:string):Promise<void>;

export function SetWhisperModel(arg1:string):Promise<void>;

export function Transcribe(arg1:string):Promise<string>;

export function WhisperStatus():Promise<main.WhisperStatus>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
